### ISSUE TITLE
Consider change to root namespace

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/binskim#1]
Microsoft.CodeAnalysis collides directly with Roslyn root namespace. As it turns out, taking a dependency in this tool on Roslyn will create a name collision (with the Roslyn Location object).

**Comment by BillyONeal** [comment]
How about `Microsoft.BinaryAnalysis` or `Microsoft.CodeAnalysis.Binary` or similar?

**Comment by michaelcfanning** [comment]
either works for me. @nguerrera? the former is more concise. the latter might be preferable if we project something of this analysis to be integrated more closely with Roslyn.
