### ISSUE TITLE
PDB could not be loaded. (E_PDB_NOT_FOUND (File not found)) when we use --sympath.

### ISSUE THREAD

**Issue by gpgera678** [Microsoft/binskim#100]
pdb files are not loading when we use --sympath. if binary file and its respective pdb in the same path then pdb files getting loaded (with/without the attribute "**--sympathy**"). otherwise, binskim throwing below exception 
**error ERR997.ExceptionLoadingPdb : BA2006 : 'MyFile.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2014 : 'MyFile.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2002 : 'MyFile.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2007 : 'MyFile.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2011 : 'MyFile.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
error ERR997.ExceptionLoadingPdb : BA2013 : 'MyFile.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))**

**Comment by Evmaus-MS** [comment]
Hey--

Sorry about the slow reply here.  Can you provide more details on the command line you were using?

/sympath basically should trigger the same logic as setting the symbols path in windbg or symchk (which searches the containing folder and select subfolders), so this isn't expected.

--Everett Maus

**Comment by Evmaus-MS** [comment]
Closing this as there wasn't any f/u.
