### ISSUE TITLE
What is the current project version and how to download?

### ISSUE THREAD

**Issue by okainov** [microsoft/binskim#1005]
Sorry for stupid question, but I'm just confused... There are a lot of different "version" all over around:

- Github Releases: latest is 2.0.0-rc1 from 2 years ago https://github.com/microsoft/binskim/releases
- Nuget link from readme: 1.9.5 https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/
- Latest commits: 4.3.0 https://github.com/microsoft/binskim/pull/997

So, question - what is the actual latest version and where do I download it?

**Comment by mkacmar** [comment]
Your best option is to build from source right now, we'll be returning to regular releases to nuget.org soon (possibly with 4.3.1 release already).

**Comment by okainov** [comment]
@mkacmar this doesn't really solve the highlighted issues with inconsistent data. Could you please push proper tags and use Github releases as well as readme?
