### ISSUE TITLE
Getting HighEntropyVACheck on dotnet core generated assembly

### ISSUE THREAD

**Issue by TravisEz13** [Microsoft/binskim#101]
We are getting `HighEntropyVACheck` on a dotnet core generated assembly defined by this csproj

https://github.com/PowerShell/PowerShell/blob/master/src/powershell-win-core/powershell-win-core.csproj
I don't think this is valid, for a dotnet assembly.

Build instructions are here:  https://github.com/PowerShell/PowerShell/blob/master/docs/building/windows-core.md

**Comment by Evmaus-MS** [comment]
Hey Travis:

Sorry about the slow reply here--you're correct that on an ILOnly assembly, HighEntropyVACheck isn't valid (and is filtered out).

However, as I understand it, the .net core Self Contained Deployments use something similar to NGEN, which means you're actually producing a native executable.  This is definitely the case on Linux, where you get ELF executables.

As I'd expect, too, the CLR headers aren't present on pwsh.exe--if you run dumpbin /clrheader pwsh.exe, you only get:
Dump of file pwsh.exe

File Type: EXECUTABLE IMAGE

  Summary

        1000 .data
        1000 .pdata
        9000 .rdata
        1000 .reloc
       20000 .rsrc
        9000 .text
        1000 .tls

Whereas on a .NET assembly, you'd get CLR header options, as in:
File Type: EXECUTABLE IMAGE

  clr Header:

              48 cb
            2.05 runtime version
            3304 [    5264] RVA [size] of MetaData Directory
               1 flags
                   IL Only
         6000037 entry point token
            8568 [     A10] RVA [size] of Resources Directory
               0 [       0] RVA [size] of StrongNameSignature Directory
               0 [       0] RVA [size] of CodeManagerTable Directory
               0 [       0] RVA [size] of VTableFixups Directory
               0 [       0] RVA [size] of ExportAddressTableJumps Directory
               0 [       0] RVA [size] of ManagedNativeHeader Directory


  Summary

        2000 .rsrc
        8000 .text


You may want to reach out to the .NET Core folks to check about the details of self contained deployments.

Thanks,
Everett Maus

**Comment by Evmaus-MS** [comment]
After going back over some things--it also does look like /highentropyva does apply to ILOnly assemblies, at least on Windows.

**Comment by TravisEz13** [comment]
`pwsh.dll` was actually the flagged binary.  I was given a workaround.
We added the following line to our common props:

` <HighEntropyVA>true</HighEntropyVA>`
https://github.com/PowerShell/PowerShell/blob/5d8999e8b5aa472139f18e9b437dbcd17d494565/PowerShell.Common.props#L107

**Comment by TravisEz13** [comment]
I don't think this is a binskim issue.  Closing.
