### ISSUE TITLE
Mach-O Binary Support

### ISSUE THREAD

**Issue by Evmaus-MS** [microsoft/binskim#163]
We currently support ELF and PE binaries.  It would be good to look into supporting Mach-O binaries (Mac OSX) as well, so that we can cover as many commonly used binary formats as possible.

**Comment by eddynaka** [comment]
With the PR above we were able to add Mach-O binary support.

**Comment by snnn** [comment]
So it will be in the next release?

**Comment by eddynaka** [comment]
Hi @snnn , yes.
we will release soon a prerelease version.

if you want to test, feel free to ping me and send me some binaries! :)
