### ISSUE TITLE
Fix output text for BA3001

### ISSUE THREAD

**Issue by michaelcfanning** [Microsoft/binskim#169]
error BA3001: PIE disabled on executable supersgd.  This means the code section will always be loaded to the same address, even if ASLR is enabled in the Linux kernel.  To address this, ensure you are compiling with '-f pie' when using clang/gcc.

1) we wrap file names and other dynamic args in single quotes by convention in output.
2) cmd arg s/be -fpie

error BA3001: PIE disabled on executable 'supersgd'.  This means the code section will always be loaded to the same address, even if ASLR is enabled in the Linux kernel.  To address this, ensure you are compiling with '-fpie' when using clang/gcc.

**Comment by Evmaus-MS** [comment]
Completed in https://github.com/Microsoft/binskim/pull/176
