### ISSUE TITLE
Update SDK to support version 2.0 of Sarif

### ISSUE THREAD

**Issue by EmmaSmith323** [microsoft/binskim#171]
Binskim should output Sarif 2.0 files for compatibility with [VS Code Extension](https://github.com/Microsoft/sarif-vscode-extension)

**Comment by Evmaus-MS** [comment]
We'll be updating to V2 once the full SARIF V2 standard has shipped.

In the meantime, there should be code for updating from v1 to v2 in the SARIF SDK repository.

**Comment by Evmaus-MS** [comment]
This code is in the 'develop' branch right now, and will ship with the next full release of BinSkim (likely 1.6.0).

**Comment by michaelcfanning** [comment]
This work is done. The command-line to use for this is the following. We should actually provide an explicit 'TwoZeroOne' value instead of current. I'll get this issue fixed on the SARIF SDK repo and we'll get that improvement into BinSkim 1.6.1.

--sarif-output-version Current
