### ISSUE TITLE
1.5.0 Did not ship with full .PDBs

### ISSUE THREAD

**Issue by Evmaus-MS** [microsoft/binskim#194]
We didn't ship 1.5.0 with full .PDB files, so scanning BinSkim.exe with itself fails at the moment due to missing .pdb files.

This may be related to the .netcoreapp2.0 conversion and how the platform specific packages are created--but we should figure out why this is occurring and if we can fix it.

**Comment by eddynaka** [comment]
All the newest releases contain the pdbs. With that, I'm closing this since v1.5 is a very old version.
