### ISSUE TITLE
Sarif output should include runInfo.commandLineArguments.

### ISSUE THREAD

**Issue by davidknise** [Microsoft/binskim#2]
According to the Sarif spec, the runInfo.commandLineArguments field is required.  Current BinSkim output has this value as null.

__Sarif Spec:__
### General { #runInfo-General }

A `runInfo` object describes the invocation of the static analysis tool that produced the issues specified
in the containing runLog object (&sect;[#runLog]).

~ IsoNote
The information in the `runInfo` object makes it possible to precisely repeat a run of a static analysis tool,
and to verify that the issues reported in the log file were generated by an appropriate invocation of the tool.
~

### `commandLineArguments` property { #runInfo-commandLineArguments }

A `runInfo` object shall contain a property named `commandLineArguments` whose value is a string
containing the command line arguments with which the tool was invoked.
This string shall not include the file name or path to the executable itself.

~ IsoExample
Suppose a tool is invoked with the command line

```
    C:\Tools\CodeScanner\CodeScanner.exe /input C:\Code\*.cc
```

Then the value of the `commandLineArguments` property should be `"/input C:\Code\*.cc"`."

**Comment by michaelcfanning** [comment]
this member has been renamed invocationInfo in the SARIF spec. it is no longer required. I have updated binskim to produce it, however, as it useful information.
