### ISSUE TITLE
Error_NoHighEntropyVA with asp dot net core app

### ISSUE THREAD

**Issue by arthurgreef** [microsoft/binskim#209]
I have an asp.netcore app and I get an error that I do not seem to able to fix. I have the following properties set.
```
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeIdentifiers>win10-x64</RuntimeIdentifiers>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

<PackageReference Include="Microsoft.AspNetCore.App" Version="2.1.5" />
```

**Comment by specialforest** [comment]
Use a workaround from https://github.com/Microsoft/msbuild/issues/2912

**Comment by michaelcfanning** [comment]
Closing this issue. Compilations that are picking up an insecure setting for csc.exe (or which aren't setting high entropy va explicity) can add the following to their project file.

<HighEntropyVA>true<HighEntropyVA>

Looks like out of box netcoreapp2.2 resolve the core problem (failure to set a secure default in the core targets/props files pulled in at compile time).
