### ISSUE TITLE
Update Docs to Clarify NuGet Installation

### ISSUE THREAD

**Issue by YoDaMa** [microsoft/binskim#211]
The quickstart uses binskim as an .exe however the way to download and run it as an .exe is not very clear, and downloading it through Nuget Package Manager on VS2017 became a nuisance. I'd recommend clarifying the process.

**Comment by YanVugenfirer** [comment]
Agree. I want to use to analyze the drivers. I fail to understand why I should add it as a package to the project.

**Comment by YoDaMa** [comment]
This issue is stale so I'm going to close it.
