### ISSUE TITLE
Error on Quickstart BinSkim analysis

### ISSUE THREAD

**Issue by YoDaMa** [Microsoft/binskim#212]
I downloaded the nuget package manually, and created a path variable to point to the tools/netcoreapp2.0/win-x64 folder. Then I ran a simple recursive analysis within my target folder

![image](https://user-images.githubusercontent.com/8214060/48809673-6ff2aa00-ecda-11e8-8303-4605b496a3ce.png)

What is causing this error? How can it be fixed?

**Comment by YoDaMa** [comment]
I believe the documentation just needs to be updated to the command 

`binskim analyze *.exe *.dll  --recurse`

**Comment by michaelcfanning** [comment]
Ouch. This was unfortunate, sorry for the inconvenience. We will fix the docs and I will look into whether we can do a better job detecting subtle command-line malformations of this kind.
