### ISSUE TITLE
BinSkim 1.5.1 showing false positives

### ISSUE THREAD

**Issue by sarojcare** [microsoft/binskim#227]
We have observed that BinSkim 1.5.1 showing false positives.

Here is a small program to demonstrate it.

**test.c**
```javascript 
int main()
{
return 0;
}
```
 
* I have compiled this program on centOS6 platform with following command and ran BinSkim on binary “a.out” generated. (gcc version 4.4.7 20120313 (Red Hat 4.4.7-18))
 
gcc -g -O2 **-Wl,-z,-relro -fpie** test.c
binSkim.exe analyze a.out
 
* Output
a.out: error BA3001: PIE disabled on executable 'a.out'.  This means the code section will always be loaded to the same address, even if ASLR is enabled in the Linux kernel.  To address this, ensure you are compiling with **'-fpie'** when using clang/gcc.
a.out: error BA3010: The GNU_RELRO segment is missing from this binary, so relocation sections in 'a.out' will not be marked as read only after the binary is loaded.  An attacker can overwrite these to redirect control flow.  Ensure you are compiling with the compiler flags **'-Wl,z,relro'** to address this.
 
 
Though I am compiling the program with required cflags yet it is reporting these errors. 

Is it a known issue? 
Whether we should ignore such issues?

**Comment by sarojcare** [comment]
Any updates..

**Comment by michaelcfanning** [comment]
@sarojcare, sorry for the egregious delay getting to this and I hope all is well with you. I am looking at this now.

**Comment by michaelcfanning** [comment]
@sarojcare , this did not repro for me in a test just now. Are you still seeing the issue in BinSkim 1.6?
