### ISSUE TITLE
"Binskim help" should retrun exit code 0, not 1

### ISSUE THREAD

**Issue by mattdesai** [microsoft/binskim#229]
it "succeeds" and prints help.
low-pri

**Comment by michaelcfanning** [comment]
@mattdesai, how are you? I looked at this and it is an artifact of using the CommandlineLibrary OSS project. I took a look at rebuilding this library to alter the behavior and it was not straightforward. We could consider updating our command line parser to use a different one (MS has one that's gaining in popularity), could consider that as an alternate.

**Comment by eddynaka** [comment]
@mattdesai , when this fix get released, the following verbs won't throw as `1`: `help`, `version`, `--version`, and `--help`.
