### ISSUE TITLE
Your wiki seems to have been hacked?

### ISSUE THREAD

**Issue by bgavrilMS** [Microsoft/binskim#235]
https://github.com/Microsoft/binskim/wiki/Publicly-Editable-wiki-bug

**Comment by scovetta** [comment]
Thanks for the note, @bgavrilMS -- @michaelcfanning This can be disabled under Settings as per [this help article](https://help.github.com/en/articles/changing-access-permissions-for-wikis).

**Comment by michaelcfanning** [comment]
'Helpful community members have pointed out your wiki security needs tightening?' might be a better title for this issue. :) Thanks for everyone for bringing this to our attention, now fixed.
