### ISSUE TITLE
BinSkim flags for Spectre if lib referenced by dll didn't have PDB

### ISSUE THREAD

**Issue by ScottLouvau** [microsoft/binskim#238]
The Spam RE2.Native DLLs were flagged for not including Spectre mitigations. In Spam, RE2.Managed uses RE2.Native, which is a DLL which references RE2.lib, containing the core RE2 types themsleves.

I fixed the projects to include in the /QSpectre flag, but still got the BinSkim error. The problem turned out to be that my LIB compilation did not produce PDBs in the output path. The DLL compilation couldn't see them, so I guess it did not copy something into the RE2.Native.pdb, and the BinSkim check in the PDB failed.

I don't know if you can detect whether an "inner" PDB was missing, but if you can't, ideally at least there would be some documentation somewhere to indicate what to do.

Ex: "Ensure your binary and all dependencies build with /QSpectre and have PDBs created so that BinSkim can confirm Spectre mitigations were enabled."

**Comment by michaelcfanning** [comment]
@ScottLouvau, I don't understand this report. The spectre analysis itself will not occur if the PDBs are missing. We use the PDB data to look at the command-line for all the compilands in the binary.

If you have a moment to show me your repro, I'd appreciate it.

**Comment by ScottLouvau** [comment]
@michaelcfanning, I tried to reproduce this but couldn't.

The situation:
I was running BinSkim against RE2.Native.dll, which had a PDB.
The build of RE2.Native referenced re2.lib, a native C++ library. It did not have a PDB in its output folder when RE2.Native.dll was run.

Running BinSkim on RE2.Native.dll reported errors about RE2.Native.dll not being compiled against Spectre-mitigated libraries, when it actually was. I think the types which came in from re2.lib didn't end up having the symbol information copied into them to verify against.

What I remember doing in source code doesn't reproduce, but you can see this issue against the Spam release before I fixed it.

Binary Repro:
- Download https://github.com/microsoft/sarif-pattern-matcher/releases/tag/1.2.1
- Run "BinSkim analyze" against all of the files in the zip.

Result:
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll : error ERR997.ExceptionLoadingPdb : BA2002 : 'RE2.Native.x64.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll : error ERR997.ExceptionLoadingPdb : BA2006 : 'RE2.Native.x64.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll : error ERR997.ExceptionLoadingPdb : BA2007 : 'RE2.Native.x64.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll: error BA2008: 'RE2.Native.x64.dll' does not enable the control flow guard (CFG) mitigation. To resolve this issue, pass /GUARD:CF on both the compiler and linker command lines. Binaries also require the /DYNAMICBASE linker option in order to enable CFG.
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll : error ERR997.ExceptionLoadingPdb : BA2011 : 'RE2.Native.x64.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll : error ERR997.ExceptionLoadingPdb : BA2013 : 'RE2.Native.x64.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll : error ERR997.ExceptionLoadingPdb : BA2014 : 'RE2.Native.x64.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x64.dll : error ERR997.ExceptionLoadingPdb : BA2024 : 'RE2.Native.x64.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll : error ERR997.ExceptionLoadingPdb : BA2002 : 'RE2.Native.x86.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll : error ERR997.ExceptionLoadingPdb : BA2006 : 'RE2.Native.x86.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll : error ERR997.ExceptionLoadingPdb : BA2007 : 'RE2.Native.x86.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll: error BA2008: 'RE2.Native.x86.dll' does not enable the control flow guard (CFG) mitigation. To resolve this issue, pass /GUARD:CF on both the compiler and linker command lines. Binaries also require the /DYNAMICBASE linker option in order to enable CFG.
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll : error ERR997.ExceptionLoadingPdb : BA2011 : 'RE2.Native.x86.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll : error ERR997.ExceptionLoadingPdb : BA2013 : 'RE2.Native.x86.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll : error ERR997.ExceptionLoadingPdb : BA2014 : 'RE2.Native.x86.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))
C:\Users\sclouvau\Downloads\Spam.1.2.1\RE2.Native.x86.dll : error ERR997.ExceptionLoadingPdb : BA2024 : 'RE2.Native.x86.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. (E_PDB_NOT_FOUND (File not found))

Next, try with the next release, https://github.com/microsoft/sarif-pattern-matcher/releases/tag/1.2.3.

Result:
Analysis completed successfully.

Repro:
- Clone https://github.com/microsoft/sarif-pattern-matcher
- In the root folder, run Build.cmd
- Run "BinSkim analyze spam\bin\Release\."

Result: No issues reported.

- Now, edit spam\RE2\RE2.props. Comment out the DebugInformationFormat and ProgramDataBaseFileName lines (~25 and ~59).
- Delete spam\bin, spam\src\RE2\bin, and spam\src\RE2.Native\bin.
- Re-run build.cmd
- Verify there are no PDBs in spam\src\RE2\bin\Release
- Re-run BinSkim.

Result: Errors about RE2.Native.x64.dll (and x86) not being built against the Spectre-mitigated libraries (didn't reproduce with BinSkim 1.6.0).

You could try syncing to the spam source version from Jun 18, 2019 when I made the fixes to see if you can get a fresh build to reproduce them.

In any case, what was confusing was E_PDB_NOT_FOUND errors when RE2.Native.x64.pdb is present. =)

**Comment by eddynaka** [comment]
@ScottLouvau , after some resource we found out that the spectre mitigation only works for release binary. So, if we get the same project with the spectre flag enabled and compile in release, the rule won't be issued.

Closing this for now.
