### ISSUE TITLE
EnableHighEntropyVirtualAddresses for 32-bit C++/CLI binaries

### ISSUE THREAD

**Issue by potrusil** [microsoft/binskim#239]
The EnableHighEntropyVirtualAddresses rule incorrectly runs for 32-bit C++/CLI executables (and probably also assemblies - not verified) and fails. The code which checks if the rule should run must be more careful with such binaries.

I have found the following code in ILSpy that may be related to the problem:

    // According to ECMA-335, II.25.3.3.1 CorFlags.Requires32Bit and Characteristics.Bit32Machine must be in sync
    // for assemblies containing managed code. However, this is not true for C++/CLI assemblies.
    if ((corflags & CorFlags.ILOnly) == 0 && (characteristics & Characteristics.Bit32Machine) != 0)
        return "x86";

**Comment by michaelcfanning** [comment]
Thanks for the problem report. I will look at this today.

**Comment by michaelcfanning** [comment]
@potrisil, I believe that 1.6 fixes this problem. Do you have a moment to test against your repro? If your issue still exists, can you advise on what version of VS you used to build your code, what project kind, etc? Thanks very much. Just reactive this issue if we still have a problem.
