### ISSUE TITLE
Consider permitting a semicolon delimited list of scan targets on the command-line

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/binskim#257]
e.g., 

binskim analyze c:\myoutput\*.exe;c:\myoutput\*.dll --recurse

This convention is very similar to the Windows %PATH% variable definition and it confuses users who attempt to utilize it (and receive a 'no valid analysis targets' message as a result.

**Comment by eddynaka** [comment]
I think we could make this change in sarif-sdk and all tools would receive this feature.
just like baseline!

**Comment by eddynaka** [comment]
Today, the `TargetFileSpecifiers` is an IEnumerable<string>, with that you can pass that like:
```
binskim analyze c:\temp\a\*.sarif c:\temp\b\*.sarif --recurse
```
