### ISSUE TITLE
Binskim on Linux

### ISSUE THREAD

**Issue by retpoline** [microsoft/binskim#261]
Is it possible to run Binskim naively on Linux or is this a supported scenario with mono?

@michaelcfanning

**Comment by scovetta** [comment]
I'm fairly certain I got this to work via WSL by first running `BuildAndTest.sh`, which creates a `src/BinSkimLinux.sln` file, and then doing:

```
dotnet build -r linux-x64 -c Release src/BinSkimLinux.sln
```

The result was:
```
$ file BinSkim
BinSkim: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.32, BuildID[sha1]=080ec01079ab2aa0009dcb829a3c7f8c22ddbf9d, stripped
```

I was also to publish the driver tool as a self-contained release:
```
cd src/BinSkim.Driver
dotnet publish BinSkim.Driver.csproj -r linux-x64 -c Release --self-contained -f netcoreapp2.0
```

I don't have .NET Core 3 installed in my WSL environment, but [/p:PublishSingleFile=true](https://docs.microsoft.com/en-us/dotnet/core/whats-new/dotnet-core-3-0) may also be useful.

**Comment by inthenets** [comment]
Thanks very much for the details! That indeed worked.

Although note that dotnet 3.1 failed to build with it, had to install dotnet 2.2.

**Comment by michaelcfanning** [comment]
@scovetta, thanks for jumping here. @inthenets, I will update the project to dotnet core 3.1. I will also capture some of this guidance in a readme.

**Comment by eddynaka** [comment]
@retpoline , would like to run the solution or just the tool?

@scovetta , right now, we are exporting as netcoreapp3.1, so we wouldn't need to install dotnet 2.x

Let us know if you face any other issue!

**Comment by michaelcfanning** [comment]
@eddynaka, just curious, have we validated that all tests, etc., are running on linux? maybe we should set up a pipeline to ensure we don't regress for this platform?

**Comment by eddynaka** [comment]
> @eddynaka, just curious, have we validated that all tests, etc., are running on linux? maybe we should set up a pipeline to ensure we don't regress for this platform?

Sure. Let me do that.

**Comment by eddynaka** [comment]
@michaelcfanning , just created a PR and it worked!
