### ISSUE TITLE
##[error]Unexpected exit code 1 returned from tool BinSkim.exe. BinSkim failed. Exit code 1 is used for all tools errors,

### ISSUE THREAD

**Issue by pomtom** [microsoft/binskim#263]
I am getting an error while building the CI Pipeline. I have created my .yml configuration like this

- task: BinSkim@3
  displayName: 'Run BinSkim Latest'
  inputs:
    InputType: 'Basic'
    Function: 'analyze'
    AnalyzeTarget: '*.dll;*.exe'
    AnalyzeVerbose: true
    AnalyzeHashes: true
    AnalyzeStatistics: true
    AnalyzeEnvironment: true
  continueOnError: true

- task: BinSkim@3
  displayName: 'Run BinSkim LatestPreRelease'
  inputs:
    InputType: 'Basic'
    Function: 'analyze'
    AnalyzeTarget: '*.dll;*.exe'
    AnalyzeVerbose: true
    AnalyzeHashes: true
    AnalyzeStatistics: true
    AnalyzeEnvironment: true
    toolVersion: 'LatestPreRelease'
  continueOnError: true

- task: BinSkim@3
  displayName: 'Run BinSkim 1.6.0'
  inputs:
    InputType: 'Basic'
    Function: 'analyze'
    AnalyzeTarget: '*.dll;*.exe'
    AnalyzeVerbose: true
    AnalyzeHashes: true
    AnalyzeStatistics: true
    AnalyzeEnvironment: true
    toolVersion: '1.6.0'
  continueOnError: true

- task: BinSkim@3
  displayName: 'Run BinSkim 1.5.0'
  inputs:
    InputType: 'Basic'
    Function: 'analyze'
    AnalyzeTarget: '*.dll;*.exe'
    toolVersion: '1.5.0'
  continueOnError: true

- task: BinSkim@3
  inputs:
    InputType: 'Basic'
    Function: 'analyze'
    AnalyzeTarget: '$(System.DefaultWorkingDirectory)\*.dll;$(System.DefaultWorkingDirectory)\*.exe'
  continueOnError: false

It also said 

{
$id: "1",
innerException: null,
message: "TF400813: The user '4223a386-bece-46a4-aa88-b0dd2bbe23cc\pomtom' is not authorized to access this resource.",
typeName: "Microsoft.TeamFoundation.Framework.Server.UnauthorizedRequestException, Microsoft.TeamFoundation.Framework.Server",
typeKey: "UnauthorizedRequestException",
errorCode: 0,
eventId: 3000
}

**Comment by michaelcfanning** [comment]
Hello, @pomtom , hope all's well.

You can pass --rich-return-code on the command-line to get a more detailed bitfield of runtime conditions that occurred during analysis. If you configure your analysis to produce a log file, would be glad to look at it. Assuming your last piece of information is related to the failure condition, I'd guess the problem has to do with your automation environment and not the tool itself. 

If it's a tool issue, it probably relates to BinSkim's attempt to retrieve a matching PDB for a file under analysis. Your log file should provide a clue for us.

> Emit a 'rich' return code consisting of a bitfield of conditions (as opposed to 0 or 1 indicating success or failure."

**Comment by eddynaka** [comment]
Hi @pomtom ,

were you able to fix the issue?
Let us know.
thank you.

**Comment by eddynaka** [comment]
Feel free to re-open or create a new issue.
I'm closing this for now.

Thank you.
