### ISSUE TITLE
Unexpected fatal runtime condition(s) observed: ExceptionRaisedInSkimmerCanAnalyze

### ISSUE THREAD

**Issue by finsharp** [microsoft/binskim#265]
Running BinSkim on Azure Devops to scan a aspnetcore webApp. I received the error below. 
From the raw logs, binSkim was executed as follows:-

`"D:\a\_sdt\Microsoft.CodeAnalysis.BinSkim.1.6.0\tools\netcoreapp2.0\win-x64\BinSkim.exe" analyze "d:\a\1\s\*.dll" --config default --recurse --verbose --hashes --statistics --output "d:\a\1\_sdt\logs\BinSkim\BinSkim.sarif"`

This was the error generated.

`##[error]Unexpected exit code 1 returned from tool BinSkim.exe. BinSkim failed. Exit code 1 is used for all tools errors, including invalid input and internal execution errors. Please review the entire console log output for more details and the reason for the error. You can also find more documentation at https://www.1eswiki.com/wiki/BinSkim_Build_Task Please refer to https://github.com/Microsoft/binskim#command-line-documentation for more info.
##[error]Unexpected exit code 1 returned from tool BinSkim.exe
`
Thanks

**Comment by finsharp** [comment]
Is analysis possible for Nuget DLLs?
Is analysis possible for DLLs without PDBs?

**Comment by michaelcfanning** [comment]
Sorry for the delay. Verified this issue in 1.6.0 and fixing now.
