### ISSUE TITLE
[WRN997.InvalidTarget] *.lib was not analyzed

### ISSUE THREAD

**Issue by hardikamin** [microsoft/binskim#292]
...
{"$schema":"https://schemastore.azurewebsites.net/schemas/json/sarif-1.0.0.json","version":"1.0.0","runs":[{"tool":{"name":"BinSkim","fullName":"BinSkim 1.6.1.0","version":"1.6.1.0","semanticVersion":"1.6.1","language":"en-US"},"invocation":{"startTime":"2020-07-21T23:47:26.296Z","endTime":"2020-07-21T23:47:26.455Z"},"files":{"file:*.lib":{}},"results":[],"configurationNotifications":[{"id":"WRN997.InvalidTarget","physicalLocation":{"uri":"file:*.lib"},"message":"**'*.lib' was not analyzed as it does not appear to be a valid file type for analysis."**,"level":"note"}]}]}
...

**Is this error expected? What are the binaries/extensions types which BinSkim supports currently?**

Ref: https://github.com/microsoft/binskim/blob/master/src/BinSkim.Driver/AnalyzeCommand.cs

**Comment by eddynaka** [comment]
Hi @hardikamin ,

when we talk about PEs, we can analyze .dll, .exe, .sys
when we talk about ELFs, we don't have a specific extension. With that, we would analyze anything that you supply.

Let us know if you still have a question.
Thank you!
