### ISSUE TITLE
test

### ISSUE THREAD

**Issue by hardikamin** [microsoft/binskim#293]
test

**Comment by hardikamin** [comment]
@michaelcfanning , please help to look into this when you get chance?

**Comment by michaelcfanning** [comment]
@hardikamin, sorry for failing to reply on this months ago. :P 

are you still seeing the issue? do you have any advice on getting a repro file together? 

i've received a second report of this, so finally getting around to chasing it down.

**Comment by hardikamin** [comment]
na
