### ISSUE TITLE
Populate `tool.driver.informationUri`

### ISSUE THREAD

**Issue by lgolding** [microsoft/binskim#294]
Since BinSkim has a tool information page (the repo) but it doesn’t have per-rule help pages, it should populate `tool.driver.informationUri`, but not `tool.driver.rules[].helpUri`.

**Comment by michaelcfanning** [comment]
Alternately, we could inject the same help page into every rule helpUri, perhaps the rules troubleshooting guide. Simple change to the base class. I can add the tool URI as well.

https://github.com/microsoft/binskim/blob/master/docs/RulesAndErrorsTroubleshootingGuide.md

**Comment by lgolding** [comment]
Yes, using the "troubleshooting guide" for `helpUri` is an improvement over using the repo URI. And good, we agree about populating `tool.driver.informationUri` with the repo URI.

Ideally there would be separate help URIs for each rule. Even with a single page, we can author anchors into the Markdown for each rule.
