### ISSUE TITLE
Documentation talks about 1.7.0, but latest is 1.6.1

### ISSUE THREAD

**Issue by Jetski5822** [microsoft/binskim#296]
**Info**

The documentation is a few places talks about version 1.7.0, but the latest version is 1.6.1

i.e. [ReleaseHistory](https://github.com/microsoft/binskim/blob/master/src/ReleaseHistory.md)

Do you have an update on when you will be shipping 1.7.0?

**Comment by michaelcfanning** [comment]
We will ship by end of day tomorrow, sorry for the delay.

**Comment by eddynaka** [comment]
@Jetski5822 , we just released the new version!

**Comment by Jetski5822** [comment]
Nice one!!! Thanks chaps
