### ISSUE TITLE
Suggested changes to rule messages

### ISSUE THREAD

**Issue by lgolding** [Microsoft/binskim#35]
In the BinSkim rule descriptor output ([binskim.rules.sarif.txt](https://github.com/Microsoft/binskim/files/189749/binskim.rules.sarif.txt)), I suggest:

Line 14: “Address Space Layour Randomization” (sp.)

Line 17: “increaseing the effectiveness” (sp.)

Line 17: “address space layout randomization” was capitalized on Line 14 but not here.

Line 29: “was built with a dependency on version of {1}” – did you mean “on a version of {1}”? or “on version {1} of {2}” (e.g., “on version 2.0 of Foo.exe”)?

Line 48: “in order to take advantage of” -- consider “to take advantage of” ;-) (and wherever that construction occurs)

Line 52: “built with a tool chain that satisfies…” – is “tool chain” our own jargon? How about “was built with tools that satisfy…”

Line 63: “… there is a greater likelihood that X, Y, and Z do not exist…” – consider “it is less likely that X, Y, and Z exist…”

**Comment by michaelcfanning** [comment]
Great feedback. Please feel free to suggest a contribution and possibly review other user-facing strings. :) If you don't get to it soon, though, I can.

**Comment by lgolding** [comment]
Fixed by #36.
