### ISSUE TITLE
PDB found, but could not be loaded (E_PDB_MAX)

### ISSUE THREAD

**Issue by DefaultRyan** [microsoft/binskim#353]
I've got my sym path and cache set, and when I enable pdb tracing, it appears that the pdb is found, but I'm getting E_PDB_MAX errors, and there is no documentation on what this error means, or how to fix it.

I get output that looks like this:
```
Microsoft.UI.Xaml.Controls.dll : error ERR997.ExceptionLoadingPdb : BA2002 : 'Microsoft.UI.Xaml.Controls.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded (E_PDB_MAX).
Microsoft.UI.Xaml.Controls.dll : warning TRC001.PdbLoad : BA2002 : Could not locate the PDB for 'Microsoft.UI.Xaml.Controls.dll'. Probing details:
  Examined PDB path: 'C:\a\1\s\BuildOutput\obj\arm64fre\controls\dev\dll\Microsoft.UI.Xaml.Controls.pdb'. HResult: E_PDB_NOT_FOUND.
  Examined PDB path: 'd:\dbg\sym\Microsoft.UI.Xaml.Controls.pdb\D370C85C6E864E32A9AEE2A6DE425F2A1\Microsoft.UI.Xaml.Controls.pdb'. HResult: S_OK.
```

The traces indicate that the PDB was found in the cache path, and I see a PDB file there. So, what's the deal with `E_PDB_MAX`?

**Comment by eddynaka** [comment]
Hi @DefaultRyan , sorry for the delay.
Looking at the dll/pdb again, it looks like the pdb is stripped and with that, binskim can not do the analysis.

**Comment by CurtHagenlocher** [comment]
I believe in previous versions of BinSkim, this returned an easier-to-understand error "(Pdb is stripped of cv (CodeView) info)".

**Comment by eddynaka** [comment]
Hi @CurtHagenlocher , with the PR marked above we fixed this issue.
soon we will release a new version.

**Comment by eddynaka** [comment]
Hi @DefaultRyan, with the PR marked above we fixed this issue.
soon we will release a new version.
