### ISSUE TITLE
ERR998.ExceptionInCanAnalyze : BA2002 : An exception was raised attempting to determine whether 'VB6ResourceHelper.dll' is a valid analysis target for check 'DoNotIncorporateVulnerableDependencies'

### ISSUE THREAD

**Issue by DotNetCoreDev** [microsoft/binskim#362]
Binskim Version  : 1.6.1

library\VB6ResourceHelper.dll : error ERR998.ExceptionInCanAnalyze : BA2002 : An exception was raised attempting to determine whether 'VB6ResourceHelper.dll' is a valid analysis target for check 'DoNotIncorporateVulnerableDependencies' (which has been disabled). The exception may have resulted from a problem related to parsing the analysis target and not specific to the rule, however. (Unexpected CodeView data signature value.)

**Comment by eddynaka** [comment]
I don't recognize this version number.

Can you also share that dll and pdb if you have?
Thank you

**Comment by DotNetCoreDev** [comment]
I think its Binskim Version : 1.6.1

**Comment by eddynaka** [comment]
How are you using? Did you use from AzureDevopsTask or from nuget.org?

Can you upgrade the version to latest?

**Comment by DotNetCoreDev** [comment]
Feeds used:
  https://pkgs.dev.azure.com/secdevtools/_packaging/SecDevTools/nuget/v3/index.json

Installing package 'Microsoft.CodeAnalysis.BinSkim' to 'C:\DEV\_sdt'.
  GET https://pkgs.dev.azure.com/secdevtools/_packaging/7dd0007f-da6c-4759-86e3-8edd2376c227/nuget/v3/registrations2-semver2/microsoft.codeanalysis.binskim/index.json
  OK https://pkgs.dev.azure.com/secdevtools/_packaging/7dd0007f-da6c-4759-86e3-8edd2376c227/nuget/v3/registrations2-semver2/microsoft.codeanalysis.binskim/index.json 54ms


Attempting to gather dependency information for package 'Microsoft.CodeAnalysis.BinSkim.1.6.1' with respect to project 'C:\DEV\_sdt', targeting 'Any,Version=v0.0'
Gathering dependency information took 71.54 ms
Attempting to resolve dependencies for package 'Microsoft.CodeAnalysis.BinSkim.1.6.1' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'Microsoft.CodeAnalysis.BinSkim.1.6.1'
Resolved actions to install package 'Microsoft.CodeAnalysis.BinSkim.1.6.1'
Retrieving package 'Microsoft.CodeAnalysis.BinSkim 1.6.1' from 'SecDevTools'.
  GET https://pkgs.dev.azure.com/secdevtools/_packaging/7dd0007f-da6c-4759-86e3-8edd2376c227/nuget/v3/flat2/microsoft.codeanalysis.binskim/1.6.1/microsoft.codeanalysis.binskim.1.6.1.nupkg
  OK https://pkgs.dev.azure.com/secdevtools/_packaging/7dd0007f-da6c-4759-86e3-8edd2376c227/nuget/v3/flat2/microsoft.codeanalysis.binskim/1.6.1/microsoft.codeanalysis.binskim.1.6.1.nupkg 333ms
Installing Microsoft.CodeAnalysis.BinSkim 1.6.1.
Adding package 'Microsoft.CodeAnalysis.BinSkim.1.6.1' to folder 'C:\DEV\_sdt'
Added package 'Microsoft.CodeAnalysis.BinSkim.1.6.1' to folder 'C:\DEV\_sdt'
Successfully installed 'Microsoft.CodeAnalysis.BinSkim 1.6.1' to C:\DEV\_sdt
Executing nuget actions took 35.67 sec
Running BinSkim...
