### ISSUE TITLE
BA2004 Error despite /ZH:SHA_256 Flag in CL

### ISSUE THREAD

**Issue by AgneLukoseviciute** [microsoft/binskim#370]
We're [working to validate](https://github.com/microsoft/react-native-windows/issues/7345) a dll in [react-native-windows ](https://github.com/microsoft/react-native-windows) using binskim and are running into an issue with BA2004 Error being hit despite enabling the /ZH:SHA_256 Flag in CL. 

binskim analyze error output:
`
C:\repos\rnw-al\vnext\target\x86\Release\Microsoft.ReactNative\Microsoft.ReactNative.dll: error BA2004: 'Microsoft.ReactNative.dll' is a native binary that directly compiles and links one or more object files which were hashed using an insecure checksum algorithm (MD5). MD5 is subject to collision attacks and its use can compromise supply chain integrity. Pass '/ZH:SHA_256' on the cl.exe command-line to enable secure source code hashing. The following modules are out of policy:
Microsoft (R) Optimizing Compiler : cxx : 19.28.29914.0 : [directly linked] (crash_min.obj,debugAssertApi.obj,memoryApi.obj,memoryLeakScope_EmptyImpl.obj,XamlFeatures.obj,XamlLibMetadataProvider.g.obj)`

Passing /ZH:SHA_256 on cl.exe worked for most object files in the project but the above ones remain. All of the above files are compiled as part of the same CL task and we've verified that the SHA_256 option is getting passed to this task through the build log. I'm pasting in that specific file here as well as including a zip file with the entire build log. Any help here would be greatly appreciated. 

CommandLineArguments:
`C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\bin\HostX64\x86\CL.exe /c /I"C:\repos\rnw-al\vnext\packages\boost.1.72.0.0\build\..\lib\native\include\\" /I"C:\repos\rnw-al\\vnext\Common" /I"C:\repos\rnw-al\\vnext\stubs" /I"C:\repos\rnw-al\\vnext\include" /I"C:\repos\rnw-al\\vnext\Shared" /I"C:\repos\rnw-al\\vnext\include\Shared" /I"C:\repos\rnw-al\\node_modules\react-native\ReactCommon\yoga" /I"C:\repos\rnw-al\node_modules\.fmt\fmt-7.1.3\\include" /I"C:\repos\rnw-al\\vnext\Microsoft.ReactNative" /I"C:\repos\rnw-al\\vnext\Microsoft.ReactNative\Fabric\platform" /I"C:\repos\rnw-al\\vnext\Microsoft.ReactNative\Pch" /I"C:\repos\rnw-al\\vnext\Microsoft.ReactNative\ReactHost" /I"C:\repos\rnw-al\\vnext\Microsoft.ReactNative\Views" /I"C:\repos\rnw-al\\vnext\\" /I"C:\repos\rnw-al\\vnext\Common" /I"C:\repos\rnw-al\\vnext\include" /I"C:\repos\rnw-al\\vnext\Shared" /I"C:\repos\rnw-al\\vnext\Shared\tracing" /I"C:\repos\rnw-al\\vnext\include\Shared" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\react\renderer\graphics\platform\cxx" /I"C:\repos\rnw-al\\node_modules\react-native\ReactCommon\yoga" /I"C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\Generated Files\\" /I"C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\\" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\jsi" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\callinvoker" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\react\nativemodule\core" /I"C:\repos\rnw-al\vnext\Microsoft.ReactNative\\" /I"C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\Generated Files\\" /I"C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\\" /I"C:\repos\rnw-al\node_modules\.folly\folly-2021.03.29.00\\" /I"C:\repos\rnw-al\node_modules\.fmt\fmt-7.1.3\include" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\callinvoker" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\jsi" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\jsiexecutor" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\react\nativemodule\core" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\react\nativemodule\samples" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\reactperflogger" /I"C:\repos\rnw-al\\node_modules\react-native\\ReactCommon\runtimeexecutor" /I"C:\repos\rnw-al\vnext\Chakra\\" /I"C:\repos\rnw-al\vnext\Shared\\" /I"C:\repos\rnw-al\vnext\Mso\\" /I"C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\Generated Files\\" /Zi /nologo /W4 /WX /diagnostics:column /sdl /MP /O1 /Oi /Oy- /GL /D NDEBUG /D FOLLY_NO_CONFIG /D NOMINMAX /D _HAS_AUTO_PTR_ETC /D RN_EXPORT= /D "__unused=[[maybe_unused]]" /D FOLLY_MOBILE=1 /D REACTWINDOWS_BUILD /D RN_PLATFORM=windows /D NOMINMAX /D FOLLY_NO_CONFIG /D RN_EXPORT= /D JSI_EXPORT= /D WIN32=0 /D WINRT=1 /D _HAS_AUTO_PTR_ETC /D PROJECT_ROOT_NAMESPACE=Microsoft::ReactNative /D USE_EDGEMODE_JSRT /D FOLLY_NO_CONFIG /D NOMINMAX /D _HAS_AUTO_PTR_ETC /D _USE_MATH_DEFINES /D RN_EXPORT= /D _WINDLL /D _UNICODE /D UNICODE /D WINRT_LEAN_AND_MEAN /D _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS /D BOOST_ALL_NO_LIB=1 /D BOOST_ERROR_CODE_HEADER_ONLY /D BOOST_NO_RTTI /D BOOST_NO_TYPEID /D BOOST_SYSTEM_SOURCE /D GTEST_HAS_RTTI=0 /D WIN32_LEAN_AND_MEAN /D NDEBUG /D ENABLE_JS_SYSTRACE_TO_ETW /D WITH_FBSYSTRACE /D ENABLE_ETW_TRACING /D WINAPI_FAMILY=WINAPI_FAMILY_APP /D __WRL_NO_DEFAULT_LIB__ /Gm- /EHsc /MD /GS /guard:cf /Gy /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR- /std:c++17 /Yu"pch.h" /Fp"C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\pch.pch" /Fo"C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\\" /Fd"C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\vc142.pdb" /Gz /TP /wd4201 /wd4505 /wd4456 /wd4458 /wd4702 /wd4068 /wd4100 /wd4101 /wd4127 /wd4189 /wd4290 /wd4309 /wd4324 /wd5205 /FIpch.h /FU"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29910\lib\x86\store\references\platform.winmd" /analyze- /FC /errorReport:prompt /await /bigobj /permissive- /utf-8  /ZH:SHA_256 /ZH:SHA_256 /bigobj /await /DWINRT_NO_MAKE_DETECTION "C:\repos\rnw-al\vnext\Chakra\ChakraHelpers.cpp" "C:\repos\rnw-al\vnext\Chakra\ChakraPlatform.cpp" "C:\repos\rnw-al\vnext\Chakra\ChakraTracing.cpp" "C:\repos\rnw-al\vnext\Chakra\ChakraUtils.cpp" "C:\repos\rnw-al\vnext\Chakra\ChakraValue.cpp" "C:\repos\rnw-al\vnext\Chakra\Utf8DebugExtensions.cpp" "C:\repos\rnw-al\vnext\Shared\AsyncStorage\AsyncStorageManager.cpp" "C:\repos\rnw-al\vnext\Shared\AsyncStorage\FollyDynamicConverter.cpp" "C:\repos\rnw-al\vnext\Shared\AsyncStorage\KeyValueStorage.cpp" "C:\repos\rnw-al\vnext\Shared\AsyncStorage\StorageFileIO.cpp" "C:\repos\rnw-al\vnext\Shared\BaseScriptStoreImpl.cpp" "C:\repos\rnw-al\vnext\Shared\cdebug.cpp" "C:\repos\rnw-al\vnext\Shared\ChakraRuntimeHolder.cpp" "C:\repos\rnw-al\vnext\Shared\CxxMessageQueue.cpp" "C:\repos\rnw-al\vnext\Shared\DevSupportManager.cpp" "C:\repos\rnw-al\vnext\Shared\Executors\WebSocketJSExecutor.cpp" "C:\repos\rnw-al\vnext\Shared\Executors\WebSocketJSExecutorFactory.cpp" "C:\repos\rnw-al\vnext\Shared\InstanceManager.cpp" "C:\repos\rnw-al\vnext\Shared\JSBigAbiString.cpp" "C:\repos\rnw-al\vnext\Shared\JSI\ChakraApi.cpp" "C:\repos\rnw-al\vnext\Shared\JSI\ChakraJsiRuntime_edgemode.cpp" "C:\repos\rnw-al\vnext\Shared\JSI\ChakraRuntime.cpp" "C:\repos\rnw-al\vnext\Shared\LayoutAnimation.cpp" "C:\repos\rnw-al\vnext\Shared\Logging.cpp" "C:\repos\rnw-al\vnext\Shared\MemoryMappedBuffer.cpp" "C:\repos\rnw-al\vnext\Shared\MemoryTracker.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\AsyncStorageModule.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\AsyncStorageModuleWin32.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\ExceptionsManagerModule.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\I18nModule.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\NetworkingModule.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\PlatformConstantsModule.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\SourceCodeModule.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\StatusBarManagerModule.cpp" "C:\repos\rnw-al\vnext\Shared\Modules\WebSocketModule.cpp" "C:\repos\rnw-al\vnext\Shared\OInstance.cpp" "C:\repos\rnw-al\vnext\Shared\PackagerConnection.cpp" "C:\repos\rnw-al\vnext\Shared\RuntimeOptions.cpp" "C:\repos\rnw-al\vnext\Shared\Threading\BatchingQueueThread.cpp" "C:\repos\rnw-al\vnext\Shared\Threading\MessageDispatchQueue.cpp" "C:\repos\rnw-al\vnext\Shared\Threading\MessageQueueThreadFactory.cpp" "C:\repos\rnw-al\vnext\Shared\tracing\tracing.cpp" "C:\repos\rnw-al\vnext\Shared\TurboModuleManager.cpp" "C:\repos\rnw-al\vnext\Shared\Utils.cpp" "C:\repos\rnw-al\vnext\Shared\WinRTWebSocketResource.cpp" "C:\repos\rnw-al\vnext\Mso\src\activeObject\activeObject.cpp" "C:\repos\rnw-al\vnext\Mso\src\crash\crash_min.cpp" "C:\repos\rnw-al\vnext\Mso\src\debugAssertApi\debugAssertApi.cpp" "C:\repos\rnw-al\vnext\Mso\src\dispatchQueue\queueService.cpp" "C:\repos\rnw-al\vnext\Mso\src\dispatchQueue\taskBatch.cpp" "C:\repos\rnw-al\vnext\Mso\src\dispatchQueue\looperScheduler.cpp" "C:\repos\rnw-al\vnext\Mso\src\dispatchQueue\taskContext.cpp" "C:\repos\rnw-al\vnext\Mso\src\dispatchQueue\taskQueue.cpp" "C:\repos\rnw-al\vnext\Mso\src\dispatchQueue\threadPoolScheduler_win.cpp" "C:\repos\rnw-al\vnext\Mso\src\dispatchQueue\uiScheduler_winrt.cpp" "C:\repos\rnw-al\vnext\Mso\src\errorCode\errorCode.cpp" "C:\repos\rnw-al\vnext\Mso\src\eventWaitHandle\eventWaitHandleImpl_win.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\cancellationTokenImpl.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\executor.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\futureImpl.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\futureTask.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\promise.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\promiseGroup.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\whenAll.cpp" "C:\repos\rnw-al\vnext\Mso\src\future\whenAny.cpp" "C:\repos\rnw-al\vnext\Mso\src\memoryApi\memoryApi.cpp" "C:\repos\rnw-al\vnext\Mso\src\memoryApi\memoryLeakScope_EmptyImpl.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\JSI\JsiAbiApi.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\JSI\JsiApiContext.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\JSValue.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\JSValueTreeReader.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\JSValueTreeWriter.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\ModuleRegistration.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\ReactPromise.cpp" "C:\repos\rnw-al\vnext\Microsoft.ReactNative.Cxx\TurboModuleProvider.cpp" ABICxxModule.cpp ABIViewManager.cpp Base\CoreNativeModules.cpp Base\CoreUIManagers.cpp Utils\BatchingEventEmitter.cpp CxxReactUWP\JSBigString.cpp DevMenuControl.cpp DynamicReader.cpp DynamicWriter.cpp GlyphViewManager.cpp IReactDispatcher.cpp IReactModuleBuilder.cpp IReactNotificationService.cpp JsiApi.cpp JsiReader.cpp JsiWriter.cpp Modules\AccessibilityInfoModule.cpp Modules\AlertModule.cpp Modules\Animated\AdditionAnimatedNode.cpp Modules\Animated\AnimatedNode.cpp Modules\Animated\AnimationDriver.cpp Modules\Animated\CalculatedAnimationDriver.cpp Modules\Animated\DecayAnimationDriver.cpp Modules\Animated\DiffClampAnimatedNode.cpp Modules\Animated\DivisionAnimatedNode.cpp Modules\Animated\EventAnimationDriver.cpp Modules\Animated\FrameAnimationDriver.cpp Modules\Animated\InterpolationAnimatedNode.cpp Modules\Animated\ModulusAnimatedNode.cpp Modules\Animated\MultiplicationAnimatedNode.cpp Modules\Animated\NativeAnimatedModule.cpp Modules\Animated\NativeAnimatedNodeManager.cpp Modules\Animated\PropsAnimatedNode.cpp Modules\Animated\SpringAnimationDriver.cpp Modules\Animated\StyleAnimatedNode.cpp Modules\Animated\SubtractionAnimatedNode.cpp Modules\Animated\TrackingAnimatedNode.cpp Modules\Animated\TransformAnimatedNode.cpp Modules\Animated\ValueAnimatedNode.cpp Modules\AppearanceModule.cpp Modules\AppStateModule.cpp Modules\AppThemeModuleUwp.cpp Modules\ClipboardModule.cpp Modules\CreateModules.cpp Modules\DeviceInfoModule.cpp Modules\DevSettingsModule.cpp Modules\I18nManagerModule.cpp Modules\ImageViewManagerModule.cpp Modules\LinkingManagerModule.cpp Modules\LogBoxModule.cpp Modules\NativeUIManager.cpp Modules\ReactRootViewTagGenerator.cpp Modules\TimingModule.cpp Modules\PaperUIManagerModule.cpp Modules\WebSocketModuleUwp.cpp NativeModulesProvider.cpp RedBoxErrorInfo.cpp RedBoxErrorFrameInfo.cpp TurboModulesProvider.cpp ReactApplication.cpp "C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\Generated Files\module.g.cpp" IReactContext.cpp ReactHost\AsyncActionQueue.cpp ReactHost\JSBundle.cpp ReactHost\JSBundle_Win32.cpp ReactHost\JSCallInvokerScheduler.cpp ReactHost\MsoUtils.cpp ReactHost\ReactContext.cpp ReactHost\ReactErrorProvider.cpp ReactHost\ReactHost.cpp ReactHost\ReactInstanceWin.cpp ReactInstanceSettings.cpp RedBoxHandler.cpp ReactNativeHost.cpp Utils\AccessibilityUtils.cpp Utils\Helpers.cpp Utils\LocalBundleReader.cpp Utils\ResourceBrushUtils.cpp Utils\UwpPreparedScriptStore.cpp Utils\UwpScriptStore.cpp Utils\ValueUtils.cpp Views\ActivityIndicatorViewManager.cpp Views\ConfigureBundlerDlg.cpp Views\ControlViewManager.cpp Views\DatePickerViewManager.cpp Views\DevMenu.cpp Views\DynamicAutomationPeer.cpp Views\DynamicAutomationProperties.cpp Views\DynamicValueProvider.cpp Views\ExpressionAnimationStore.cpp Views\FlyoutViewManager.cpp Views\FrameworkElementViewManager.cpp Views\Image\ImageViewManager.cpp Views\Image\ReactImage.cpp Views\Image\ReactImageBrush.cpp Views\Impl\ScrollViewUWPImplementation.cpp Views\Impl\SnapPointManagingContentControl.cpp Views\KeyboardEventHandler.cpp Views\PaperShadowNode.cpp Views\PickerViewManager.cpp Views\PopupViewManager.cpp Views\RawTextViewManager.cpp Views\ReactRootControl.cpp Views\RefreshControlManager.cpp Views\RootViewManager.cpp Views\ScrollContentViewManager.cpp Views\ScrollViewManager.cpp Views\ShadowNodeBase.cpp Views\ShadowNodeRegistry.cpp Views\SIPEventHandler.cpp Views\SliderViewManager.cpp Views\SwitchViewManager.cpp Views\TextInputViewManager.cpp Views\TextViewManager.cpp Views\TouchEventHandler.cpp Views\ViewControl.cpp Views\ViewManagerBase.cpp Views\ViewPanel.cpp Views\ViewViewManager.cpp Views\VirtualTextViewManager.cpp Views\XamlFeatures.cpp XamlLoadState.cpp XamlView.cpp XamlUIService.cpp ReactPackageBuilder.cpp IReactPropertyBag.cpp ReactRootView.cpp RedBox.cpp ReactSupport.cpp TestHook.cpp QuirkSettings.cpp ViewManagersProvider.cpp XamlHelper.cpp "C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\Generated Files\XamlTypeInfo.Impl.g.cpp" "C:\repos\rnw-al\\vnext\\build\x86\Release\Microsoft.ReactNative\Generated Files\XamlLibMetadataProvider.g.cpp"`

Build Log:
[Microsoft.ReactNative_Release_Win32_Build_2021-05-05T13_43_50.0866920-05_00.zip](https://github.com/microsoft/binskim/files/6429770/Microsoft.ReactNative_Release_Win32_Build_2021-05-05T13_43_50.0866920-05_00.zip)

**Comment by eddynaka** [comment]
Hi @AgneLukoseviciute ,

Just marked the PR that improved the BA2004 rule.
I will close the issue for now.
Please, re-open or create a new one.

Thank you for reporting!
