### ISSUE TITLE
`libuv.dll` generates PDB_MAX error at analysis time.

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/binskim#397]
1. Install [LibUv 1.9.0](https://www.nuget.org/packages/Libuv/1.9.0)
2. Run `binskim analyze --sympath Cache*c:\symbols;SRV*http://msdl.microsoft.com/download/symbols`

I'm seeing output like the following:

> libuv.dll : error ERR997.ExceptionLoadingPdb : BA2007 : 'libuv.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded (E_PDB_MAX).

Note the `E_PDB_MAX` return code (where `E_PDB_NOT_FOUND` is returned without the `--sympath` argument. We should investigate this unexpected error code.

**Comment by michaelcfanning** [comment]
@eddynaka @yongyan-gh @shaopeng-gh

**Comment by shaopeng-gh** [comment]
I will check this.
