### ISSUE TITLE
Add native GitHub continuous code security and quality analysis

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/binskim#425]
- [CodeQL](https://github.com/github/codeql) is an open source code scanning tool for discovering vulnerabilities across a codebase

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by eddynaka** [comment]
Hi @aleks-ivanov ,

My suggestion: don't enable CodeQL for push + dependabot because it will generate this issue:
```
Workflows triggered by Dependabot on the "push" event run with read-only access. Uploading Code Scanning results requires write access. To use Code Scanning with Dependabot, please ensure you are using the "pull_request" event for this workflow and avoid triggering on the "push" event for Dependabot branches. See https://docs.github.com/en/code-security/secure-coding/configuring-code-scanning#scanning-on-push for more information on how to configure these events
```

This applies everywhere.
