### ISSUE TITLE
Add a CI pipeline with GitHub Actions

### ISSUE THREAD

**Issue by aleks-ivanov** [microsoft/binskim#427]
- Create a pipeline for Continuous Integration (build and test validation, test log generation, assemblies generation) with GitHub Actions

Pipeline Foundation is **a non-profit initiative** with the sole purpose of giving back to the IT community by assisting OSS projects with DevOps implementations and best practices.

Built with ❤ by [Pipeline Foundation](https://pipeline.foundation).

**Comment by eddynaka** [comment]
Hi @aleks-ivanov ,
thanks for starting this but today, we are already using AzurePipelines to add some compliance tasks.
With that, I'm closing the PR and the issue.

Thank you again for the effort! I really like it!
