### ISSUE TITLE
Add C++ dialect information to compiler inventory telemetry

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/binskim#472]
Relevant proposed dialects follow. The presence or absence of /std provides this data.  If missing it is dictated by /Tp or /Tc.  Then again /clr and cx are controlled with other switches.

```
C99, C11, C14, C22, CX, CLR, C++14, C++17, and C++20
```

@eddynaka, @shaopeng-gh, @yongyan-gh, high priority.

**Comment by shaopeng-gh** [comment]
ack. I will work on this one.
