### ISSUE TITLE
[BinSkim] - Build is broken due to BinSkim failures 

### ISSUE THREAD

**Issue by umapathyven** [microsoft/binskim#540]
Hi

I am getting the below BinSkim exception in the build pipeline. We don’t think our project has any direct dependency on “Microsoft.Data.SqlClient.SNI.dll”.

Any idea how to fix this issue ?. This is a blocking issue for me. is there any work around to resolve this issue ?.

ERR997.ExceptionLoadingPdb : BA2013 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded.
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2006 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2007 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2011 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2013 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'InitializeStackProtection' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2014 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'DoNotDisableStackProtectionForFunctions' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x64\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2024 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'EnableSpectreMitigations' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2002 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'DoNotIncorporateVulnerableDependencies' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2006 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'BuildWithSecureTools' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2007 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'EnableCriticalCompilerWarnings' because its PDB could not be loaded. 
C:\__w\1\s\test\DataStore.Kusto.FunctionalTest\bin\Release\net5.0\runtimes\win-x86\native\Microsoft.Data.SqlClient.SNI.dll : error ERR997.ExceptionLoadingPdb : BA2011 : 'Microsoft.Data.SqlClient.SNI.dll' was not evaluated for check 'EnableStackProtection' because its PDB could not be loaded. 

Failed  build

https://microsoft.visualstudio.com/Universal%20Store/\_build/results?buildId=43093459&view=logs&j=15dfcb1a-0989-5cf6-3160-3e181e44de87&t=f7c6dd8c-934a-51e0-5ea7-0003e02827a9&l=130

**Comment by eddynaka** [comment]
Hi @umapathyven ,

Microsoft.Data.SqlClient.SNI ships two PDBs a public and internal.
The public pdb is stripped and the internal contains everything.

To BinSkim run completely, you must use the internal, if that is not possible, you might need to remove that binary from the analysis.

**Comment by umapathyven** [comment]
we don't directly use 'Microsoft.Data.SqlClient.SNI in my project', so I am not sure how to use Internal PDB. 

how to remove that binary from the analysis ?.

**Comment by umapathyven** [comment]
For BinSkim failures in onebranch, we should engage onebranchsupport for a quick turnaround. I resolved this issue by adding ' analyzeTargetGlob' in binskim in .yml. file. There is an option to exclude/include files in binskim scanning

      binskim:
        break: true # always break the build on binskim issues. You can disable it by setting to 'false'
        # There is a bug associated with this dll. The PDB file is only published on a private MS server
        # and the pipeline is running in an environment that can't access it.
        analyzeTargetGlob: '+:file|**\bin\**\*.dll;-:file|**\Microsoft.Data.SqlClient.SNI.dll'
      policheck:
