### ISSUE TITLE
Flaky unit test: MultithreadedAnalyzeCommand_ReturnCommonPathRootFromTargetSpecifiersIfOneExists

### ISSUE THREAD

**Issue by pharring** [microsoft/binskim#658]
The MultithreadedAnalyzeCommand_ReturnCommonPathRootFromTargetSpecifiersIfOneExists unit test fails occasionally.
For example, one of the random seeds is 63096267.6169

```
Expected sb.Length to be 0 because The test was expecting 'c:\' but found 'C:\' when shuffled with seed '63096267.6169'.
    , but found 87 (difference of 87).
```

It fails on this test case:
```csharp
new
{
    TargetFileSpecifiers = new[]
    {
        @"c:\*.dll",
        @"c:\*.dll",
        @"C:\*.DLL"
    },
    ExpectedCommonPath = @"c:\"
}
```

The ReturnCommonPathRootFromTargetSpecifiersIfOneExists algorithm is case-insensitive, and all three inputs are equivalent, so it's fair to select any one of them. Due to random shuffling, there's a 1 in 3 chance it'll be the upper-case version causing the test case to fail.

I think the fix is to make the success/fail test case insensitive too.
i.e. instead of:
```csharp
commonPath != testCase.ExpectedCommonPath
```
do this:
```csharp
!string.Equals(commonPath, testCase.ExpectedCommonPath, StringComparison.OrdinalIgnoreCase))
```

**Comment by marmegh** [comment]
Thanks @pharring.
