### ISSUE TITLE
If I added flags right according to analysis suggestion for rule BA3002, BA3010.

### ISSUE THREAD

**Issue by XiaoningJin** [microsoft/binskim#728]
Hi, @michaelcfanning @eddynaka 

I want to consult you guys to help me to see if I added flags right to fit rule BA3002, BA3010. I appreciate your ideas and time, thanks a lot!

I have analysis artifact on ADO pipeline with **Linux** VMImage using BinSkim v1.9.5, it reports the artifact broken rules (BA3002, BA3010, BA3011) as below. So according to analysis suggestion, I have added these flags using [same method/syntax](https://github.com/intel/ros2_intel_realsense/blob/master/realsense_ros2_camera/CMakeLists.txt#L22) to `compiler/linker` to `clang` and re-analysis. I found **ONLY** rule **BA3011** can works as expected, but others (**BA3003, BA3010**) can't work. I guess maybe I missed something or misunderstood something.

`set(LD_FLAGS "${LD_FLAGS} -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now")`
`set(LDFLAGS "${LDFLAGS} -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now")`

> **BA3002** - Error
> Value: [GNU_STACK](https://sourceware.org/binutils/docs/ld/Options.html#:~:text=%E2%80%98-,noexecstack%E2%80%99,-Marks%20the%20object) segment on 'ABC.NX.nss' is missing, which means the stack will likely be loaded as executable.  Ensure you are using an up to date compiler and passing `'-z noexecstack'` to the compiler.
> ______________________________________
> **BA3010** - Error
> Value: The [GNU_RELRO](https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc#:~:text=All-,%2DWl%2C%2Dz%2Crelro,-Read%2Donly%20segments) segment is missing from this binary, so relocation sections in 'ABC.NX.nss' will not be marked as read only after the binary is loaded.  An attacker can overwrite these to redirect control flow.  Ensure you are compiling with the compiler flags `'-Wl,z,relro'` to address this.
> ______________________________________
> **BA3011** - Error
> Value: The [BIND_NOW](https://developers.redhat.com/blog/2018/03/21/compiler-and-linker-flags-gcc#:~:text=All-,%2DWl%2C%2Dz%2Cnow,-Disable%20lazy%20binding) flag is missing from this binary, so relocation sections in 'ABC.NX.nss' will not be marked as read only after the binary is loaded.  An attacker can overwrite these to redirect control flow.  Ensure you are compiling with the compiler flags `'-Wl,z,now'` to address this.

The analyzing log details here:
> Analyzing...
> D:\a\_work\1\a\Publish\ABC.NX.nss: error BA3002: GNU_STACK segment on 'ABC.NX.nss' is missing, which means the stack will likely be loaded as executable.  Ensure you are using an up to date compiler and passing '-z noexecstack' to the compiler.
> D:\a\_work\1\a\Publish\ABC.NX.nss: error BA3004: 'ABC.NX.nss' is using debugging dwarf version '4'. The dwarf version 5 contains more information and should be used. To enable the debugging version 5 use '-gdwarf-5'.
> D:\a\_work\1\a\Publish\ABC.NX.nss: error BA3010: The GNU_RELRO segment is missing from this binary, so relocation sections in 'ABC.NX.nss' will not be marked as read only after the binary is loaded.  An attacker can overwrite these to redirect control flow.  Ensure you are compiling with the compiler flags '-Wl,z,relro' to address this.
> 
> Done. 1 files scanned.
> Analysis completed successfully.

Please feel free to let me know any update! 
Thanks a lot!

**Comment by michaelcfanning** [comment]
@shaopeng-gh 

Hello! My knowledge of compiler behavior here is not deep. Shaopeng may be help to investigate further.

One obvious possibility, however, is that your command-line is not properly formed and I wonder specifically if specifying -Wl repeatedly is resetting the bundle of arguments passed to the linker (which would explain why only `-z, now` is being honored).

Does this work?

`set(LDFLAGS "${LDFLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")`

**Comment by XiaoningJin** [comment]
> @shaopeng-gh
> 
> Hello! My knowledge of compiler behavior here is not deep. Shaopeng may be help to investigate further.
> 
> One obvious possibility, however, is that your command-line is not properly formed and I wonder specifically if specifying -Wl repeatedly is resetting the bundle of arguments passed to the linker (which would explain why only `-z, now` is being honored).
> 
> Does this work?
> 
> `set(LDFLAGS "${LDFLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")`

Great ideas! I'll try it and update you!

**Comment by XiaoningJin** [comment]
> > @shaopeng-gh
> > Hello! My knowledge of compiler behavior here is not deep. Shaopeng may be help to investigate further.
> > One obvious possibility, however, is that your command-line is not properly formed and I wonder specifically if specifying -Wl repeatedly is resetting the bundle of arguments passed to the linker (which would explain why only `-z, now` is being honored).
> > Does this work?
> > `set(LDFLAGS "${LDFLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")`
> 
> Great ideas! I'll try it and update you!

I have used your ideas below, but they also can't work as expected. :-( 
So, I guess maybe I need deeper research our toolchain supports it or not...

`set(LD_FLAGS "${LD_FLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")`
`set(LDFLAGS "${LDFLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")`
```

**Comment by shaopeng-gh** [comment]
@XiaoningJin thanks for reaching out! 
I think the rule should be working fine for clang build in Linux, we have working tests under:
https://github.com/microsoft/binskim/blob/main/src/Test.FunctionalTests.BinSkim.Rules/FunctionalTestData/BA3002.DoNotMarkStackAsExecutable/Pass/clang.noexecstack
https://github.com/microsoft/binskim/blob/main/src/Test.FunctionalTests.BinSkim.Rules/FunctionalTestData/BA3002.DoNotMarkStackAsExecutable/Fail/clang.execstack

could it be your parameters did not reach the clang as expected.
Could you try with 
1. https://github.com/search?l=Makefile&q=clang+noexecstack&type=Code
2. in addition to LDFLAGS also set CFLAGS `--noexecstack`

if can't figure out we may be able to take a look at your make file.

**Comment by XiaoningJin** [comment]
> @XiaoningJin thanks for reaching out! I think the rule should be working fine for clang build in Linux, we have working tests under: https://github.com/microsoft/binskim/blob/main/src/Test.FunctionalTests.BinSkim.Rules/FunctionalTestData/BA3002.DoNotMarkStackAsExecutable/Pass/clang.noexecstack https://github.com/microsoft/binskim/blob/main/src/Test.FunctionalTests.BinSkim.Rules/FunctionalTestData/BA3002.DoNotMarkStackAsExecutable/Fail/clang.execstack
> 
> could it be your parameters did not reach the clang as expected. Could you try with
> 
> 1. https://github.com/search?l=Makefile&q=clang+noexecstack&type=Code
> 2. in addition to LDFLAGS also set CFLAGS `--noexecstack`
> 
> if can't figure out we may be able to take a look at your make file.

Thanks a lot, @shaopeng-gh 

I'll also add it to CXXFLAGS & CFLAGS to see if get expected result and update you!

**Comment by XiaoningJin** [comment]
> 



> > @XiaoningJin thanks for reaching out! I think the rule should be working fine for clang build in Linux, we have working tests under: https://github.com/microsoft/binskim/blob/main/src/Test.FunctionalTests.BinSkim.Rules/FunctionalTestData/BA3002.DoNotMarkStackAsExecutable/Pass/clang.noexecstack https://github.com/microsoft/binskim/blob/main/src/Test.FunctionalTests.BinSkim.Rules/FunctionalTestData/BA3002.DoNotMarkStackAsExecutable/Fail/clang.execstack
> > could it be your parameters did not reach the clang as expected. Could you try with
> > 
> > 1. https://github.com/search?l=Makefile&q=clang+noexecstack&type=Code
> > 2. in addition to LDFLAGS also set CFLAGS `--noexecstack`
> > 
> > if can't figure out we may be able to take a look at your make file.
> 
> Thanks a lot, @shaopeng-gh
> 
> I'll also add it to CXXFLAGS & CFLAGS to see if get expected result and update you!

@shaopeng-gh, 

I have added CXXFLAGS & CFLAGS as below (part of CMakeLists.txt), it can't work as expected. 

```
if(NX)
  set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} -Wl,-z,noexecstack,-z,relro,-z,now")
  set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} -Wl,-z,noexecstack,-z,relro,-z,now")
  set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "${CMAKE_STATIC_LINKER_FLAGS_RELEASE} -Wl,-z,noexecstack,-z,relro,-z,now")
  set(CXXFLAGS "${CXXFLAGS} --noexecstack")
  set(CFLAGS "${CFLAGS} --noexecstack")
  set(LD_FLAGS "${LD_FLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")
  set(LDFLAGS "${LDFLAGS} -Wl,-z,noexecstack,-z,relro,-z,now")

  add_compile_options(
    -Wno-error=unused-command-line-argument
  )

endif()
```

**Comment by shaopeng-gh** [comment]
Let me do a test with a Clang in Linux with helloworld C program and Makefile, hold on :)

**Comment by XiaoningJin** [comment]
> Let me do a test with a Clang in Linux with helloworld C program and Makefile, hold on :)

Actually, my target device is Switch, and I use BinSkim analysis it under Linux ADO VMImage.

**Comment by shaopeng-gh** [comment]
@XiaoningJin 
Just tried, works well on my Linux VM, can produce both positive and negative case, checked using Binskim.
I think you can 
1. try run `make` using this most simplified version on your VM, if works then could be something wrong with the code in your makefile.
2. If this does not work in your VM, it is possible that the clang in your VM does not support it you may do some research. It happened to me before that clang in macOS does not support a certain flag while support in Linux. 
Also you can try if install and use latest version of clang in your vm makes any difference. 


hello.c:
```c
#include <stdio.h> 
  
int main(void)
{
    printf("Hello, World!\n");
}
```

Makefile:
```makefile
# the compiler to use
CC = clang-14

# compiler flags:
CFLAGS  = -g -Wall -z noexecstack -z relro -z now
# CFLAGS  = -g -Wall -z execstack

#files to link:
LFLAGS = 

TARGET = hello
OUTFILE = clang-14.noexecstack.relro.now
# OUTFILE = clang-14.execstack.no_relro.no_now
  
all: $(TARGET)
  
$(TARGET): $(TARGET).c
	$(CC) $(CFLAGS) -o $(OUTFILE) $(TARGET).c $(LFLAGS)
```

**Comment by XiaoningJin** [comment]
> @XiaoningJin Just tried, works well on my Linux VM, can produce both positive and negative case, checked using Binskim. I think you can
> 
> 1. try run `make` using this most simplified version on your VM, if works then could be something wrong with the code in your makefile.
> 2. If this does not work in your VM, it is possible that the clang in your VM does not support it you may do some research. It happened to me before that clang in macOS does not support a certain flag while support in Linux.
>    Also you can try if install and use latest version of clang in your vm makes any difference.
> 
> hello.c:
> 
> ```c
> #include <stdio.h> 
>   
> int main(void)
> {
>     printf("Hello, World!\n");
> }
> ```
> 
> Makefile:
> 
> ```makefile
> # the compiler to use
> CC = clang-14
> 
> # compiler flags:
> CFLAGS  = -g -Wall -z noexecstack -z relro -z now
> # CFLAGS  = -g -Wall -z execstack
> 
> #files to link:
> LFLAGS = 
> 
> TARGET = hello
> OUTFILE = clang-14.noexecstack.relro.now
> # OUTFILE = clang-14.execstack.no_relro.no_now
>   
> all: $(TARGET)
>   
> $(TARGET): $(TARGET).c
> 	$(CC) $(CFLAGS) -o $(OUTFILE) $(TARGET).c $(LFLAGS)
> ```

Many thanks, @shaopeng-gh 

I'll try your ideas and update you!

**Comment by XiaoningJin** [comment]
> > Let me do a test with a Clang in Linux with helloworld C program and Makefile, hold on :)
> 
> Actually, my target device is Switch, and I use BinSkim analysis it under Linux ADO VMImage. So, there may something Switch affects the compiler/linker flag adding.
> 
> This [stackoverflow thread](https://stackoverflow.com/questions/40657182/stacks-are-executable-even-with-noexecstack) talks about a dependency is using a different toolchain and prevents the `noexecstack` from working as expected.

Many thanks, @shaopeng-gh 

Your ideas are great! 👍 
Today my workmate and I together have double check `CMakeLists.txt`, we have tried make our ABC.NX.nss a mini "Hello word" program. Finally, we have found the dependency (SDK) of ABC.NX.nss broken these rules, so they prevent ABC.NX.nss to fit BinSkim rules as expected. 😄

**Comment by shaopeng-gh** [comment]
Glad to help! :slightly_smiling_face:

**Comment by shaopeng-gh** [comment]
@XiaoningJin I would like to hear your feedback what our doc / error message can improve that would have helped you troubleshoot? And for that purpose, could you provide more details how do you know what dependency cause breaking the rule? Which SDK is causing problem? Is it related to the specific vm with specific toolchain installed, or related to target Switch, or the settings in makefile.
Just to get more info, in case people encounter similar issue. 🙂

**Comment by XiaoningJin** [comment]
> @XiaoningJin I would like to hear your feedback what our doc / error message can improve that would have helped you troubleshoot? And for that purpose, could you provide more details how do you know what dependency cause breaking the rule? Which SDK is causing problem? Is it related to the specific vm with specific toolchain installed, or related to target Switch, or the settings in makefile. Just to get more info, in case people encounter similar issue. 🙂

Sure, @shaopeng-gh 😄 

We use `readelf -Wd ABC.NX.nss` to find ABC.NX.nss share dependencies. From results we can see it depends on `glslc.nss` and `nnSdk.nss` in SwitchSDK13. Then, we used BinSkim to analysis `glslc.nss` and `nnSdk.nss`, we found they broken rule `BA3002, BA3004, BA3010, BA3011`, they prevent ABC.NX.nss to fit these rules as expected.

- glslc.nss broken: `BA3002, BA3010, BA3011`.
- nnSdk.nss broken: `BA3002, BA3004, BA3010, BA3011`. 

Please take a look at this snapshot, we can see ABC.NX.nss needs `glslc.nss` and `nnSdk.nss`, but its FLAGS is `BIND_NOW` (I guess `-Wl,-z,now` works, so as first no rule `BA3011` was broken.)
![image](https://user-images.githubusercontent.com/116610814/201235519-0acb8532-54af-4b3d-b229-37dc072dcd89.png)

Here is our rough `bash script (find_shared_denp.bash )` to find share dependencies may use to refer:

```
#!/usr/bin/env bash

if [ -z "$1" ]; then
	echo "Find dependency of <target>"
	echo "Usage: $0 <target>"
    exit 1
fi

file_nm="$1"
all_output=$(readelf -Wd $file_nm 2> /dev/null)
echo "Looking dependency of $file_nm:"
echo -e "All: $all_output"

echo -e "\nDependenices of $file_nm:"
printf '%s\n' "echo $all_output" | grep "NEEDED" | while IFS= read -r line
do
   echo "$line"
done

echo -e "\nFlags:"
printf '%s\n' "echo $all_output" | grep "FLAGS" | while IFS= read -r line
do
   echo "$line"
done

echo -e "\nDependencies' dependencies:"
printf '%s\n' "echo $all_output" | grep "NEEDED" | awk -F"[" '{print $2}' | sed 's/.$//' | while IFS= read -r line
do
    for nss in $line; do
    	if [ -f $nss ]; then
    		nss_dep=$(readelf -Wd $nss | egrep "(FLAGS|NEEDED)")
		if [ ! -z "$nss_dep" ]; then
    		    echo "$nss depends on $nss_dep"
		else
    		    echo "$nss no dependency"
		fi
    	fi
    done
done
```

For BinSkimRules.md rules `BA3010` error section, I guess there is a very and very tiny flag usage may need update (If I'm not wrong) to `-z` instead of `z`, also for `BA3011`. (Sorry for I just focus on these rules we artifact broken.)
https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-ba3010enablereadonlyrelocations
https://github.com/microsoft/binskim/blob/main/docs/BinSkimRules.md#rule-ba3011enablebindnow

**Comment by XiaoningJin** [comment]
So, I'd like to close this thread.
