### ISSUE TITLE
recurse option does not work

### ISSUE THREAD

**Issue by sepidehkh** [Microsoft/binskim#78]
I'm running the following (dlls I want to check are directly placed under bin directory):

`BinSkim.exe analyze bin -c default -r --output BinSkim.report`

And I get this error:

```
error ERR997.NoValidAnalysisTargets : No valid analysis targets were specified.

Analysis did not complete due to one or more unrecoverable execution conditions.
Unexpected fatal runtime condition(s) observed: NoValidAnalysisTargets
```

**Comment by leovms** [comment]
I ran into something similar. Try adding `/*` to your path, as in:

`BinSkim.exe analyze bin/* -c default -r --output BinSkim.report`

**Comment by michaelcfanning** [comment]
This answer is correct, you need a wildcard specifier for recurse to work properly
