### ISSUE TITLE
Support for command line length limit extension

### ISSUE THREAD

**Issue by rodsan** [Microsoft/binskim#80]
Users are encountering an issue with long sympaths, which ends up giving them an error. There is no support ticket currently associated with this, but the thread title is "Information about BinSkim error"

**Comment by Evmaus-MS** [comment]
To phrase this more formally:

At the moment, the only way to configure a BinSkim run's parameters is via the command line.

If you need to do something like specifying a large number of symbols file locations, especially if you're deep in a file structure, you need to pass all of them on the command line.  Users have run up against the Window's command line limit of 8191 characters.

To avoid this, it would be nice to have an option for passing scan parameters into the tool via a route other than the command line (file, etc.) that isn't limited to 8000 characters.

**Comment by michaelcfanning** [comment]
1.4.2 published to nuget.org resolves this issue. Users can now specify a response file by prefixing a response file name with the '@' character. This file can contain arbitrary Binskim arguments (separated by newlines). eg
binskim.exe analyze myFile.dll @myAdditionalSettings.rsp
