### ISSUE TITLE
Exit Code Differentiation

### ISSUE THREAD

**Issue by Evmaus-MS** [Microsoft/binskim#82]
Current behavior:  any error when running BinSkim, regardless of severity/etc., will give an exit code of '1'.  This includes issues that often happen if you run the tool across products with rely on third party libraries, like not finding PDB files.

This makes it difficult to integrate the tool into other orchestration using the 'recurse' option--where we may expect to be missing private symbols for some libraries.

Expected behavior:  Missing PDB files should be logged as an error, users integrating the tool should be able to differentiate that case from other errors via the exit code.

**Comment by michaelcfanning** [comment]
This issue is resolved by release 1.4.2. PDB missing is now indicated by a 0x20 bit set in the return code provided on passing --rich-return-code to the binskim.exe command-line.
