### ISSUE TITLE
Where is sarif-2.1.0-rtm.6.json schema file?

### ISSUE THREAD

**Issue by pig837** [microsoft/binskim#837]
Hi, I used binskim v2.0.0-rc1, and got a .sarif file generated by the tool.

I tried to open the .sarif file using vscode with Sarif Viewer v3.3.5, but I couldn't open the file.

But, I found a workaround.

1. Open the .sarif file using notepad, etc. (generated by binskim v2.0.0-rc1)
2. Modify line 2 on the file
    From.   "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.6.json",
    To.   "$schema": "https://schemastore.azurewebsites.net/schemas/json/sarif-2.1.0-rtm.5.json",
3. Open the .sarif file using vscode (Sarif Viewer v3.3.5)
4. Profit!

I tested the following:
- sarif-2.1.0-rtm.5.json (I can open the URL)
- sarif-2.1.0-rtm.6.json (I can't open the URL)
  "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

![sarif-2 1 0-rtm 5 json](https://user-images.githubusercontent.com/10391680/225512397-bffedbb3-c379-4643-b5fc-fa78724b1cbf.png)

![sarif-2 1 0-rtm 6 json](https://user-images.githubusercontent.com/10391680/225512412-ef316f25-fcd0-4b82-b549-b23454b0ad6a.png)

Please fix this problem, thx.

**Comment by michaelcfanning** [comment]
Oops, yes, will fix.
