### ISSUE TITLE
Suggestion to use  --verbose should be removed

### ISSUE THREAD

**Issue by quasarea** [microsoft/binskim#842]
When scanning dlls without pdbs, I'm getting:
```
...
Done. 12 files scanned.

One or more rules was disabled for an analysis target, as it was determined not to be applicable to it (this is a common condition). Pass --verbose on the command-line for more information.
```

and I'm calling binskim with:
```
--level Error Warning Note 
--kind Fail Pass Review Open NotApplicable Informational
```

so output is exactly same as with --verbose, minus the warning on verbose deprecation
```
BINSKIM : warning WRN997.ObsoleteOption : Option '--verbose' is obsolete.  Use 'use --level and --kind' instead.
```

My expectation would be to not get this suggestion at all with arguments I use

**Comment by shaopeng-gh** [comment]
You are correct the message is wrong. I have fixed this in release 4.1.0 branch, we will merge it to main after testing.
