### ISSUE TITLE
BA2004 - EnableSecureSourceCodeHashing   Error message only shows SHA1 when not SHA256

### ISSUE THREAD

**Issue by schlaman-ms** [Microsoft/binskim#857]
Whatever the scanned binary's Hashing is, if it is not SHA256 then it assumes SHA-1 and messages accordingly.

The current BA2004 Rule logic is as follows:

if (foundChecksum != Sha256)
{
   Generates the following BA2004 message:  '{0}' is a managed binary compiled with an insecure (**SHA-1)** source code hashing algorithm.
}

This needs to change to put what the actual found Hashing algorithm is instead of the hardcoded "SHA-1"

**Comment by suvamM** [comment]
Resolved via https://github.com/microsoft/binskim/pull/868
