### ISSUE TITLE
Is it true that I can pass an input file list?

### ISSUE THREAD

**Issue by ncook-hxgn** [microsoft/binskim#956]
# Input File Lists

For some reason, I had it in my head that BinSkim would accept a text file listing paths to binaries to be scanned, so I tried it with BinSkim 1.9.4,  and it didn't work. 

I guess this feature doesn't exist - and I did in fact imagine it - or, I'm doing it wrong.. (binskim rightly telling me that this .txt file isn't suitable for binskim to analyze). 

```
"C:\Windows\system32\cmd.exe" /D /E:ON /V:OFF /S /C "CALL "D:\azure\agent\_work\_temp\xxxxxxxxxx.cmd""
Analyzing...
BINSKIM : warning WRN997.ObsoleteOption : Option '--verbose' is obsolete.  Use 'use --level and --kind' instead.
D:\azure\agent\_work\263\s\myproject\Build\signme_binaries.txt : note WRN997.InvalidTarget : 'signme_binaries.txt' was not analyzed as it does not appear to be a valid file type for analysis.

Done. 1 files scanned.
Analysis completed successfully.

One or more targets was skipped entirely as it was determined to be an invalid target for analysis. Pass --verbose on the command-line for more information.
```

However, this would be super useful to me. 

I've written some Directory.Build.targets and Directory.Solution.targets that allow a build to generate a list of binaries it produced. I currently use this list with the `-ifl` parameter of AzureSignTool, such that I sign all the binaries I built. 

It would be wonderful if I could use the same list with BinSkim, especially as BinSkim will verify the validity of the signature on the binaries I pass it. It would also help me improve the signal/noise ratio that comes from scanning a directory for *.dll, when such a directory is filled with binaries from nuget packages that I don't have symbols for.. I only want to scan binaries I've built.

When looking around for some documentation or an example of this feature (which I apparently imagined), I found these two issues that hinted that such functionality does exist:
https://github.com/Microsoft/binskim/issues/195 
https://github.com/microsoft/binskim/issues/624

#### Platform & applicability
- all

#### Links/Additional Information

Existing issues in this repo that hint that I am passing a scannable-files-manifest file wrongly:
- [https://github.com/Microsoft/binskim/issues/195](https://github.com/Microsoft/binskim/issues/195) 
- [https://github.com/microsoft/binskim/issues/624](https://github.com/microsoft/binskim/issues/624)

Example of `ifl` parameter being used with AzureSignTool (see Example usage section):
- [https://github.com/vcsjones/AzureSignTool#azure-sign-tool](https://github.com/vcsjones/AzureSignTool#azure-sign-tool)

#### Implementation Notes

Maybe it's already implemented and I just couldn't find the docs? 
If not, a new parameter `-ifl` for `--input-file-list` would be lovely. It should expect a text file containing full paths to the binaries that the binskim user wants scan results for

#### How to resolve

Maybe it's already implemented and I just couldn't find the docs? (I'm hoping for this and a RTFM-flavoured answer :D)

**Comment by shaopeng-gh** [comment]
Yes, BinSkim supports target file list
please try
`analyze @"C:\filelist.txt" --level Error;Warning;Note`
and in the filelist.txt put the full path of each file you want to scan in separated lines:
```
C:\vs2012.exe
C:\vs2013.exe
```

**Comment by ncook-hxgn** [comment]
I think  that's what I tried, but it didn't work, as per original post

.. is the `@` necessary (or is that PowerShell?)

I ran this:
```cmd
"C:\__t\Microsoft.CodeAnalysis.BinSkim.2.0.0-rc1\tools\netcoreapp3.1\win-x64\BinSkim.exe" analyze "C:\__w\1\s\src\filelist.txt" ^
  --config "default" ^
  --output "C:\__w\1\s\CodeAnalysis\binskim.sarif" ^
  --level Error;Warning;Note
```

and I got 
```cmd
Analyzing...
C:\__w\1\s\src\filelist.txt : note WRN997.InvalidTarget : 'filelist.txt' was not analyzed as it does not appear to be a valid file type for analysis.

Done. 1 files scanned.
Analysis completed successfully.

One or more targets was skipped entirely as it was determined to be an invalid target for analysis. Pass --verbose on the command-line for more information.
```

I get the same result with 1.9.4 and 1.9.5 also

**Comment by ncook-hxgn** [comment]
.. you totally do need the `@`.
