### ISSUE TITLE
Special-case compiler generated `dummy.obj` file that fires `BA2004`

### ISSUE THREAD

**Issue by michaelcfanning** [microsoft/binskim#983]
From a .NET native C# UWP App.

We need to potentially special-case this finding as not under user control. This specific `dummy.obj` compiland is emitted by compiler tools.

When taking a fix, the very precise thing to do would be to hard-code/check the specific MD5 hash for this obj (i.e., don't simply perform a name check). Also ensure the compiler is reported as MASM.

> error BA2004: 'MicrosoftSecurityBackgroundApp.dll' is a native binary that directly compiles and links one or more object files which were hashed using an insecure checksum algorithm (MD5). MD5 is subject to collision attacks and its use can compromise supply chain integrity. Pass '/ZH:SHA_256' on the cl.exe command-line to enable secure source code hashing. The following modules are out of policy: 
Microsoft (R) Optimizing Compiler : masm : 11.0.65502.0 : [directly linked] (dummy.obj)

**Comment by shaopeng-gh** [comment]
Confirmed with the same finding. Will work on this fix.
