### ISSUE TITLE
Question about releases?

### ISSUE THREAD

**Issue by aursulis** [microsoft/binskim#998]
Hi, I've seen pull requests like https://github.com/microsoft/binskim/pull/997 (Release 4.3.0) go by, however both the Github releases page (https://github.com/microsoft/binskim/releases) and Nuget (https://www.nuget.org/packages/Microsoft.CodeAnalysis.BinSkim/) still have only outdated versions. Is this unexpected, or are users just supposed to build binskim from source? Thanks.

**Comment by shaopeng-gh** [comment]
Thanks for the feedback. 
Yes, Please build BinSkim from source to get the latest functionalities.
We are not releasing new packages in NuGet recently.
